# Generated by Django 2.1.1 on 2019-07-19 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SoupModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soup_origin_id', models.CharField(max_length=10, verbose_name='源网站ID')),
                ('title', models.CharField(max_length=128, verbose_name='标题')),
                ('head_url', models.URLField(null=True, verbose_name='头图')),
                ('pic_urls', models.TextField(null=True, verbose_name='内容图片地址')),
                ('page_url', models.URLField(null=True, verbose_name='源网页')),
                ('content', models.TextField(null=True, verbose_name='简介')),
                ('how_to_do', models.TextField(null=True, verbose_name='制作步骤')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
